DROP TABLE IF EXISTS IMAGE;
CREATE TABLE IMAGE (
image_id INT AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(100) NOT NULL,
image_metadata VARCHAR(4000) NOT NULL,
objectLabel VARCHAR(100)
);
CREATE TABLE OBJECT (
pid INT AUTO_INCREMENT PRIMARY KEY,
objectDetected VARCHAR(100));
